Common CI improvements
51Degrees/common-ci pull request #20
Opened 2023-06-09 09:38 UTC by pi-alexander-popel

- Add a custom composite action that installs language runtimes
- Add support for caching assets
- Move test results publishing to a separate composite action
- Remove non-existing argument in a call to pull-request-to-main.ps1

2023-06-21 10:46 UTC, ben51degrees requested changes

2023-06-21 10:46 UTC, ben51degrees commented on DESIGN.md
In this document, could you add some description of how the asset caching is used?
Just so that it's clear to someone new to the code what's going on.

2023-06-21 12:00 UTC, pi-alexander-popel commented on DESIGN.md
Pushed the changes, PTAL.

2023-06-22 08:01 UTC, ben51degrees approved these changes

2023-06-22 08:02 UTC, merged